@baseUrl = http://localhost:{{$dotenv PORT}}/api
# @name GetPosts

POST {{baseUrl}}/auth/signup
content-type: application/json

{
  "username": "1236",
  "password":"1236"
}
###

POST {{baseUrl}}/auth/signin
content-type: application/json

{
  "username": "1237",
  "password":"1236"
}
###
@postId = {{GetPosts.response.body.0._id}}
POST {{baseUrl}}/new/createproduct
content-type: application/json

{
  "title": "hi",
  "description": "does this work?",
}

####
PATCH {{baseUrl}}/user/profile/6418e86f4753523c2add9140
content-type: application/json

{
  "name": "Miguel Arias",
  "email": "argenis803@gmail.com"
}
