@baseUrl = http://localhost:{{$dotenv PORT}}/api

POST {{baseUrl}}/auth/signup
content-type: application/json

{
  "username": "1236",
  "password":"1236"
}
###

POST {{baseUrl}}/auth/signin
content-type: application/json

{
  "username": "1237",
  "password":"1236"
}
###
POST {{baseUrl}}/new/createproduct
content-type: application/json

{
  "title": "hi",
  "author": "ObjectId('64148b72d22819d1625f7380')",
  "description": "does this work?"
}